### GENERAL SETTINGS ###

# Site settings
title: Andrés Pereira
description: "Game Developer Portfolio"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "https://AGPO93.github.io/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#6a8c52" # lower bar, and footer #c0d8f6
  primary_rgb: "106,140,82" # Needed in some places for the transparency effect.
  secondary: "#313131" # top bar
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/in/agpo93/
  - title: facebook
    url: https://www.facebook.com/andres.pereiraorco

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Bristol,
    - United Kingdom.
email: AGPO93@gmail.com



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Andrés Pereira
    position: Games Technology Student
    text: University of the West of England, Bristol
    img: profileAndres.jpg
    social:
      - title: envelope #use for email address
        url: mailto:AGPO93@gmail.com
      - title: linkedin
        url: https://www.linkedin.com/in/agpo93/

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Game developer with interest in the fields of Robotics and Software Development."
